fix: use native mkdirp replacement to address webpack-dev-middleware changes
Fixing `TypeError: localFs.mkdirp is not a function`, caused by the migration from `memfs@3` to `memfs@4` in webpack/webpack-dev-middleware#1693, where `mkdirp` was removed. See: https://github.com/streamich/memfs/releases/tag/v4.2.0

Refs: #441